/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auditLog from "../auditLog.js";
import type * as auth_actions_changePassword from "../auth/actions/changePassword.js";
import type * as auth_actions_login from "../auth/actions/login.js";
import type * as auth_actions_logout from "../auth/actions/logout.js";
import type * as auth_mutations_internalCreateSession from "../auth/mutations/internalCreateSession.js";
import type * as auth_mutations_internalDeleteSession from "../auth/mutations/internalDeleteSession.js";
import type * as auth_mutations_internalRecordLoginAttempt from "../auth/mutations/internalRecordLoginAttempt.js";
import type * as auth_mutations_internalUpsertSetting from "../auth/mutations/internalUpsertSetting.js";
import type * as auth_mutations_refreshSession from "../auth/mutations/refreshSession.js";
import type * as auth_queries_internalCheckLoginRateLimit from "../auth/queries/internalCheckLoginRateLimit.js";
import type * as auth_queries_internalGetSettingValue from "../auth/queries/internalGetSettingValue.js";
import type * as auth_queries_internalValidateSession from "../auth/queries/internalValidateSession.js";
import type * as auth_queries_validateSession from "../auth/queries/validateSession.js";
import type * as auth_shared_computeLoginRateLimit from "../auth/shared/computeLoginRateLimit.js";
import type * as auth_shared_generateToken from "../auth/shared/generateToken.js";
import type * as auth_shared_getValidSession from "../auth/shared/getValidSession.js";
import type * as auth_shared_rateLimitWindowMs from "../auth/shared/rateLimitWindowMs.js";
import type * as auth_shared_requireAuth from "../auth/shared/requireAuth.js";
import type * as auth_shared_sessionDurations from "../auth/shared/sessionDurations.js";
import type * as costTracking_actions_internalCheckBudgetAlert from "../costTracking/actions/internalCheckBudgetAlert.js";
import type * as costTracking_mutations_internalMarkBudgetAlertSent from "../costTracking/mutations/internalMarkBudgetAlertSent.js";
import type * as costTracking_queries_getCostByProvider from "../costTracking/queries/getCostByProvider.js";
import type * as costTracking_queries_getCostHistory from "../costTracking/queries/getCostHistory.js";
import type * as costTracking_queries_getMonthlyCost from "../costTracking/queries/getMonthlyCost.js";
import type * as costTracking_queries_internalCheckBudgetReached from "../costTracking/queries/internalCheckBudgetReached.js";
import type * as costTracking_queries_internalGetMonthlyCost from "../costTracking/queries/internalGetMonthlyCost.js";
import type * as costTracking_shared_assertWithinBudget from "../costTracking/shared/assertWithinBudget.js";
import type * as costTracking_shared_budgetReachedMessage from "../costTracking/shared/budgetReachedMessage.js";
import type * as costTracking_shared_computeMonthlyCost from "../costTracking/shared/computeMonthlyCost.js";
import type * as costTracking_shared_getBudgetThreshold from "../costTracking/shared/getBudgetThreshold.js";
import type * as costTracking_shared_isMonthlyBudgetReached from "../costTracking/shared/isMonthlyBudgetReached.js";
import type * as crons from "../crons.js";
import type * as customFields from "../customFields.js";
import type * as dashboard_queries_activeJobsCount from "../dashboard/queries/activeJobsCount.js";
import type * as dashboard_queries_monthlySpend from "../dashboard/queries/monthlySpend.js";
import type * as dashboard_queries_recentResearch from "../dashboard/queries/recentResearch.js";
import type * as dashboard_queries_upcomingSchedules from "../dashboard/queries/upcomingSchedules.js";
import type * as earnings_actions_internalCheckEarningsTriggers from "../earnings/actions/internalCheckEarningsTriggers.js";
import type * as earnings_actions_internalFetchAllEarnings from "../earnings/actions/internalFetchAllEarnings.js";
import type * as earnings_actions_internalTestCheckEarningsTriggers from "../earnings/actions/internalTestCheckEarningsTriggers.js";
import type * as earnings_mutations_internalRecordTriggeredRun from "../earnings/mutations/internalRecordTriggeredRun.js";
import type * as earnings_mutations_internalUpdateScheduleLastRunAt from "../earnings/mutations/internalUpdateScheduleLastRunAt.js";
import type * as earnings_mutations_internalUpsertEarnings from "../earnings/mutations/internalUpsertEarnings.js";
import type * as earnings_queries_getEarningsByStockId from "../earnings/queries/getEarningsByStockId.js";
import type * as earnings_queries_getEarningsSummaryAll from "../earnings/queries/getEarningsSummaryAll.js";
import type * as earnings_queries_internalCheckAlreadyTriggered from "../earnings/queries/internalCheckAlreadyTriggered.js";
import type * as earnings_queries_internalCheckAlreadyTriggeredForQuarter from "../earnings/queries/internalCheckAlreadyTriggeredForQuarter.js";
import type * as earnings_queries_internalGetEarningsByDate from "../earnings/queries/internalGetEarningsByDate.js";
import type * as earnings_queries_internalGetEarningsForStocks from "../earnings/queries/internalGetEarningsForStocks.js";
import type * as earnings_queries_internalGetEarningsSchedules from "../earnings/queries/internalGetEarningsSchedules.js";
import type * as earnings_queries_internalGetStocksByIds from "../earnings/queries/internalGetStocksByIds.js";
import type * as earnings_queries_internalListAllStocks from "../earnings/queries/internalListAllStocks.js";
import type * as earnings_shared_addDays from "../earnings/shared/addDays.js";
import type * as earnings_shared_formatDate from "../earnings/shared/formatDate.js";
import type * as earnings_shared_getCurrentReportingQuarter from "../earnings/shared/getCurrentReportingQuarter.js";
import type * as earnings_shared_getQuarterKey from "../earnings/shared/getQuarterKey.js";
import type * as earnings_shared_getTodayInTimezone from "../earnings/shared/getTodayInTimezone.js";
import type * as earnings_shared_handleAggregateMode from "../earnings/shared/handleAggregateMode.js";
import type * as earnings_shared_handleEachMode from "../earnings/shared/handleEachMode.js";
import type * as earnings_shared_resolveEligibleStocks from "../earnings/shared/resolveEligibleStocks.js";
import type * as earnings_shared_resolveSelectedStocks from "../earnings/shared/resolveSelectedStocks.js";
import type * as earnings_shared_sleepMs from "../earnings/shared/sleepMs.js";
import type * as http from "../http.js";
import type * as lib_anthropicBatchHelpers from "../lib/anthropicBatchHelpers.js";
import type * as lib_asyncIterators from "../lib/asyncIterators.js";
import type * as lib_exchangeTimezones from "../lib/exchangeTimezones.js";
import type * as lib_finnhub_isEligibleType from "../lib/finnhub/isEligibleType.js";
import type * as lib_finnhub_mapExchange from "../lib/finnhub/mapExchange.js";
import type * as lib_finnhub_rankSearchResults from "../lib/finnhub/rankSearchResults.js";
import type * as lib_finnhub_sortRank from "../lib/finnhub/sortRank.js";
import type * as lib_finnhub_types from "../lib/finnhub/types.js";
import type * as lib_logger from "../lib/logger.js";
import type * as notifications_actions_detectTelegramChatId from "../notifications/actions/detectTelegramChatId.js";
import type * as notifications_actions_internalDispatchBatchNotification from "../notifications/actions/internalDispatchBatchNotification.js";
import type * as notifications_actions_internalDispatchJobNotification from "../notifications/actions/internalDispatchJobNotification.js";
import type * as notifications_actions_internalSendEmail from "../notifications/actions/internalSendEmail.js";
import type * as notifications_actions_internalSendTelegramMessage from "../notifications/actions/internalSendTelegramMessage.js";
import type * as notifications_actions_sendTestEmail from "../notifications/actions/sendTestEmail.js";
import type * as notifications_actions_sendTestTelegram from "../notifications/actions/sendTestTelegram.js";
import type * as notifications_shared_buildResearchEmailHtml from "../notifications/shared/buildResearchEmailHtml.js";
import type * as notifications_shared_escapeHtml from "../notifications/shared/escapeHtml.js";
import type * as notifications_shared_formatDuration from "../notifications/shared/formatDuration.js";
import type * as notifications_shared_sanitizeForTelegramMarkdown from "../notifications/shared/sanitizeForTelegramMarkdown.js";
import type * as prompts_mutations_clonePrompt from "../prompts/mutations/clonePrompt.js";
import type * as prompts_mutations_createPrompt from "../prompts/mutations/createPrompt.js";
import type * as prompts_mutations_deletePrompt from "../prompts/mutations/deletePrompt.js";
import type * as prompts_mutations_updatePrompt from "../prompts/mutations/updatePrompt.js";
import type * as prompts_queries_getPrompt from "../prompts/queries/getPrompt.js";
import type * as prompts_queries_internalGetPrompt from "../prompts/queries/internalGetPrompt.js";
import type * as prompts_queries_listPrompts from "../prompts/queries/listPrompts.js";
import type * as prompts_shared_promptType from "../prompts/shared/promptType.js";
import type * as providers_anthropic from "../providers/anthropic.js";
import type * as providers_anthropicManagedAgents from "../providers/anthropicManagedAgents.js";
import type * as providers_anthropicManagedAgents_basename from "../providers/anthropicManagedAgents/basename.js";
import type * as providers_anthropicManagedAgents_collectCompletedResult from "../providers/anthropicManagedAgents/collectCompletedResult.js";
import type * as providers_anthropicManagedAgents_downloadReportFile from "../providers/anthropicManagedAgents/downloadReportFile.js";
import type * as providers_anthropicManagedAgents_isMarkdown from "../providers/anthropicManagedAgents/isMarkdown.js";
import type * as providers_anthropicManagedAgents_pickReportFile from "../providers/anthropicManagedAgents/pickReportFile.js";
import type * as providers_anthropicManagedAgents_resolveIdleSession from "../providers/anthropicManagedAgents/resolveIdleSession.js";
import type * as providers_anthropicModelLimits from "../providers/anthropicModelLimits.js";
import type * as providers_constants from "../providers/constants.js";
import type * as providers_formatOpenaiAdapter from "../providers/formatOpenaiAdapter.js";
import type * as providers_index from "../providers/index.js";
import type * as providers_managedAgentProvisioning_agentName from "../providers/managedAgentProvisioning/agentName.js";
import type * as providers_managedAgentProvisioning_buildCoordinatorSystemPrompt from "../providers/managedAgentProvisioning/buildCoordinatorSystemPrompt.js";
import type * as providers_managedAgentProvisioning_buildToolset from "../providers/managedAgentProvisioning/buildToolset.js";
import type * as providers_managedAgentProvisioning_ensureAgent from "../providers/managedAgentProvisioning/ensureAgent.js";
import type * as providers_managedAgentProvisioning_ensureEnvironment from "../providers/managedAgentProvisioning/ensureEnvironment.js";
import type * as providers_managedAgentProvisioning_ensureManagedAgentResources from "../providers/managedAgentProvisioning/ensureManagedAgentResources.js";
import type * as providers_managedAgentProvisioning_findAgentByName from "../providers/managedAgentProvisioning/findAgentByName.js";
import type * as providers_managedAgentProvisioning_hashParams from "../providers/managedAgentProvisioning/hashParams.js";
import type * as providers_openai from "../providers/openai.js";
import type * as providers_openai_buildOpenAIResponseCreateParams from "../providers/openai/buildOpenAIResponseCreateParams.js";
import type * as providers_openai_estimateOpenAICost from "../providers/openai/estimateOpenAICost.js";
import type * as providers_openai_renderOutputTextWithCitations from "../providers/openai/renderOutputTextWithCitations.js";
import type * as providers_openai_renderResearchMarkdown from "../providers/openai/renderResearchMarkdown.js";
import type * as providers_openaiResponses from "../providers/openaiResponses.js";
import type * as providers_types from "../providers/types.js";
import type * as research_actions_checkJobHealth from "../research/actions/checkJobHealth.js";
import type * as research_actions_internalPollFormat from "../research/actions/internalPollFormat.js";
import type * as research_actions_internalPollJob from "../research/actions/internalPollJob.js";
import type * as research_actions_internalProcessWebhookEvent from "../research/actions/internalProcessWebhookEvent.js";
import type * as research_actions_internalRecoverStaleFormatting from "../research/actions/internalRecoverStaleFormatting.js";
import type * as research_actions_internalRecoverStaleJobs from "../research/actions/internalRecoverStaleJobs.js";
import type * as research_actions_internalReformatByTicker from "../research/actions/internalReformatByTicker.js";
import type * as research_actions_internalReformatResearchJob from "../research/actions/internalReformatResearchJob.js";
import type * as research_actions_internalStartFormat from "../research/actions/internalStartFormat.js";
import type * as research_actions_internalStartResearch from "../research/actions/internalStartResearch.js";
import type * as research_mutations_cancelJob from "../research/mutations/cancelJob.js";
import type * as research_mutations_createAndStartResearch from "../research/mutations/createAndStartResearch.js";
import type * as research_mutations_createResearchJob from "../research/mutations/createResearchJob.js";
import type * as research_mutations_deleteJob from "../research/mutations/deleteJob.js";
import type * as research_mutations_internalApplyReformattedResult from "../research/mutations/internalApplyReformattedResult.js";
import type * as research_mutations_internalBeginBackfillFormat from "../research/mutations/internalBeginBackfillFormat.js";
import type * as research_mutations_internalBeginFormattingPhase from "../research/mutations/internalBeginFormattingPhase.js";
import type * as research_mutations_internalClearFormatExternalId from "../research/mutations/internalClearFormatExternalId.js";
import type * as research_mutations_internalCompleteFormattedJob from "../research/mutations/internalCompleteFormattedJob.js";
import type * as research_mutations_internalDrainProviderQueue from "../research/mutations/internalDrainProviderQueue.js";
import type * as research_mutations_internalIncrementAttempts from "../research/mutations/internalIncrementAttempts.js";
import type * as research_mutations_internalIncrementFormatAttempts from "../research/mutations/internalIncrementFormatAttempts.js";
import type * as research_mutations_internalLogCost from "../research/mutations/internalLogCost.js";
import type * as research_mutations_internalSetFormatExternalId from "../research/mutations/internalSetFormatExternalId.js";
import type * as research_mutations_internalUpdateJobStatus from "../research/mutations/internalUpdateJobStatus.js";
import type * as research_mutations_retryJob from "../research/mutations/retryJob.js";
import type * as research_mutations_toggleFavorite from "../research/mutations/toggleFavorite.js";
import type * as research_queries_getActiveJobs from "../research/queries/getActiveJobs.js";
import type * as research_queries_getJob from "../research/queries/getJob.js";
import type * as research_queries_internalDebugJobFormatting from "../research/queries/internalDebugJobFormatting.js";
import type * as research_queries_internalDebugListRecentJobs from "../research/queries/internalDebugListRecentJobs.js";
import type * as research_queries_internalFindLatestCompletedJobByTicker from "../research/queries/internalFindLatestCompletedJobByTicker.js";
import type * as research_queries_internalGetConcurrencyJobs from "../research/queries/internalGetConcurrencyJobs.js";
import type * as research_queries_internalGetJob from "../research/queries/internalGetJob.js";
import type * as research_queries_internalGetJobByExternalId from "../research/queries/internalGetJobByExternalId.js";
import type * as research_queries_internalGetJobByFormatExternalId from "../research/queries/internalGetJobByFormatExternalId.js";
import type * as research_queries_internalGetStaleFormattingJobs from "../research/queries/internalGetStaleFormattingJobs.js";
import type * as research_queries_internalGetStaleRunningJobs from "../research/queries/internalGetStaleRunningJobs.js";
import type * as research_queries_internalGetStock from "../research/queries/internalGetStock.js";
import type * as research_queries_internalSummarizeResearchResultSizes from "../research/queries/internalSummarizeResearchResultSizes.js";
import type * as research_queries_listFavorites from "../research/queries/listFavorites.js";
import type * as research_queries_listJobs from "../research/queries/listJobs.js";
import type * as research_queries_listResults from "../research/queries/listResults.js";
import type * as research_queries_searchResults from "../research/queries/searchResults.js";
import type * as research_shared_applyCompletedResult from "../research/shared/applyCompletedResult.js";
import type * as research_shared_applyFailedResult from "../research/shared/applyFailedResult.js";
import type * as research_shared_clearFormatTrackingFields from "../research/shared/clearFormatTrackingFields.js";
import type * as research_shared_completeFormatJob from "../research/shared/completeFormatJob.js";
import type * as research_shared_countH2 from "../research/shared/countH2.js";
import type * as research_shared_countH3 from "../research/shared/countH3.js";
import type * as research_shared_dispatchPostCompleteSideEffects from "../research/shared/dispatchPostCompleteSideEffects.js";
import type * as research_shared_formatMode from "../research/shared/formatMode.js";
import type * as research_shared_formatPollInitialDelayMs from "../research/shared/formatPollInitialDelayMs.js";
import type * as research_shared_getOpenAIApiKey from "../research/shared/getOpenAIApiKey.js";
import type * as research_shared_getProviderApiKey from "../research/shared/getProviderApiKey.js";
import type * as research_shared_handleFormatTimeout from "../research/shared/handleFormatTimeout.js";
import type * as research_shared_handlePollCompleted from "../research/shared/handlePollCompleted.js";
import type * as research_shared_handleStartError from "../research/shared/handleStartError.js";
import type * as research_shared_isPipelineJob from "../research/shared/isPipelineJob.js";
import type * as research_shared_isTerminal from "../research/shared/isTerminal.js";
import type * as research_shared_jobHardTimeoutMs from "../research/shared/jobHardTimeoutMs.js";
import type * as research_shared_jobStatus from "../research/shared/jobStatus.js";
import type * as research_shared_loadActiveJobsForConcurrency from "../research/shared/loadActiveJobsForConcurrency.js";
import type * as research_shared_loadDisplayActiveJobs from "../research/shared/loadDisplayActiveJobs.js";
import type * as research_shared_loadFormattingJobs from "../research/shared/loadFormattingJobs.js";
import type * as research_shared_loadJob from "../research/shared/loadJob.js";
import type * as research_shared_loadJobForBackfill from "../research/shared/loadJobForBackfill.js";
import type * as research_shared_maxRetries from "../research/shared/maxRetries.js";
import type * as research_shared_maybeTimeoutOrReschedule from "../research/shared/maybeTimeoutOrReschedule.js";
import type * as research_shared_missingKeyMessage from "../research/shared/missingKeyMessage.js";
import type * as research_shared_parseRetryDelayMs from "../research/shared/parseRetryDelayMs.js";
import type * as research_shared_reformatStarted from "../research/shared/reformatStarted.js";
import type * as research_shared_resolvePrompt from "../research/shared/resolvePrompt.js";
import type * as research_shared_schedulePoll from "../research/shared/schedulePoll.js";
import type * as research_shared_scheduleProviderQueueDrain from "../research/shared/scheduleProviderQueueDrain.js";
import type * as research_shared_scheduleStart from "../research/shared/scheduleStart.js";
import type * as research_shared_sleep from "../research/shared/sleep.js";
import type * as research_shared_sourceMarkdown from "../research/shared/sourceMarkdown.js";
import type * as research_shared_statusMessage from "../research/shared/statusMessage.js";
import type * as researchConcurrency from "../researchConcurrency.js";
import type * as researchFormatCore from "../researchFormatCore.js";
import type * as researchFormatPrepass from "../researchFormatPrepass.js";
import type * as researchJobSearchMetadata from "../researchJobSearchMetadata.js";
import type * as schedules_actions_internalExecuteRunNow from "../schedules/actions/internalExecuteRunNow.js";
import type * as schedules_actions_internalExecuteScheduledRun from "../schedules/actions/internalExecuteScheduledRun.js";
import type * as schedules_actions_internalScheduleNextRun from "../schedules/actions/internalScheduleNextRun.js";
import type * as schedules_mutations_createSchedule from "../schedules/mutations/createSchedule.js";
import type * as schedules_mutations_deleteSchedule from "../schedules/mutations/deleteSchedule.js";
import type * as schedules_mutations_internalCreateScheduledJob from "../schedules/mutations/internalCreateScheduledJob.js";
import type * as schedules_mutations_internalUpdateScheduleNextRun from "../schedules/mutations/internalUpdateScheduleNextRun.js";
import type * as schedules_mutations_runScheduleNow from "../schedules/mutations/runScheduleNow.js";
import type * as schedules_mutations_toggleGlobalPause from "../schedules/mutations/toggleGlobalPause.js";
import type * as schedules_mutations_toggleSchedule from "../schedules/mutations/toggleSchedule.js";
import type * as schedules_mutations_updateSchedule from "../schedules/mutations/updateSchedule.js";
import type * as schedules_queries_getGlobalPauseStatus from "../schedules/queries/getGlobalPauseStatus.js";
import type * as schedules_queries_getSchedule from "../schedules/queries/getSchedule.js";
import type * as schedules_queries_getScheduleHistory from "../schedules/queries/getScheduleHistory.js";
import type * as schedules_queries_getUpcomingRuns from "../schedules/queries/getUpcomingRuns.js";
import type * as schedules_queries_internalGetGlobalPauseStatus from "../schedules/queries/internalGetGlobalPauseStatus.js";
import type * as schedules_queries_internalGetSchedule from "../schedules/queries/internalGetSchedule.js";
import type * as schedules_queries_internalListStocks from "../schedules/queries/internalListStocks.js";
import type * as schedules_queries_listSchedules from "../schedules/queries/listSchedules.js";
import type * as schedules_shared_computeNextRunAt from "../schedules/shared/computeNextRunAt.js";
import type * as schedules_shared_earningsConfigValidator from "../schedules/shared/earningsConfigValidator.js";
import type * as schedules_shared_getDatePartsInTimezone from "../schedules/shared/getDatePartsInTimezone.js";
import type * as schedules_shared_getUtcTimestampFromTzParts from "../schedules/shared/getUtcTimestampFromTzParts.js";
import type * as schedules_shared_matchesField from "../schedules/shared/matchesField.js";
import type * as schedules_shared_parseCron from "../schedules/shared/parseCron.js";
import type * as schedules_shared_parseField from "../schedules/shared/parseField.js";
import type * as schedules_shared_stockSelectionValidator from "../schedules/shared/stockSelectionValidator.js";
import type * as seed_mutations_internalBackfillCostLogs from "../seed/mutations/internalBackfillCostLogs.js";
import type * as seed_mutations_internalSeedPrompts from "../seed/mutations/internalSeedPrompts.js";
import type * as settings_mutations_upsertSetting from "../settings/mutations/upsertSetting.js";
import type * as settings_queries_getSetting from "../settings/queries/getSetting.js";
import type * as settings_shared_protectedSettingKeys from "../settings/shared/protectedSettingKeys.js";
import type * as stocks_actions_resolveStockSymbol from "../stocks/actions/resolveStockSymbol.js";
import type * as stocks_actions_searchStockSymbols from "../stocks/actions/searchStockSymbols.js";
import type * as stocks_mutations_addStock from "../stocks/mutations/addStock.js";
import type * as stocks_mutations_deleteStock from "../stocks/mutations/deleteStock.js";
import type * as stocks_mutations_updateStock from "../stocks/mutations/updateStock.js";
import type * as stocks_queries_getStock from "../stocks/queries/getStock.js";
import type * as stocks_queries_getStockByTicker from "../stocks/queries/getStockByTicker.js";
import type * as stocks_queries_listStocks from "../stocks/queries/listStocks.js";
import type * as stocks_queries_listTags from "../stocks/queries/listTags.js";
import type * as stocks_shared_getFinnhubApiKey from "../stocks/shared/getFinnhubApiKey.js";
import type * as stocks_shared_maxQueryLength from "../stocks/shared/maxQueryLength.js";
import type * as stocks_shared_minQueryLength from "../stocks/shared/minQueryLength.js";
import type * as stocks_shared_normalizeLookupQuery from "../stocks/shared/normalizeLookupQuery.js";
import type * as stocks_shared_requireValidSession from "../stocks/shared/requireValidSession.js";
import type * as validation from "../validation.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  auditLog: typeof auditLog;
  "auth/actions/changePassword": typeof auth_actions_changePassword;
  "auth/actions/login": typeof auth_actions_login;
  "auth/actions/logout": typeof auth_actions_logout;
  "auth/mutations/internalCreateSession": typeof auth_mutations_internalCreateSession;
  "auth/mutations/internalDeleteSession": typeof auth_mutations_internalDeleteSession;
  "auth/mutations/internalRecordLoginAttempt": typeof auth_mutations_internalRecordLoginAttempt;
  "auth/mutations/internalUpsertSetting": typeof auth_mutations_internalUpsertSetting;
  "auth/mutations/refreshSession": typeof auth_mutations_refreshSession;
  "auth/queries/internalCheckLoginRateLimit": typeof auth_queries_internalCheckLoginRateLimit;
  "auth/queries/internalGetSettingValue": typeof auth_queries_internalGetSettingValue;
  "auth/queries/internalValidateSession": typeof auth_queries_internalValidateSession;
  "auth/queries/validateSession": typeof auth_queries_validateSession;
  "auth/shared/computeLoginRateLimit": typeof auth_shared_computeLoginRateLimit;
  "auth/shared/generateToken": typeof auth_shared_generateToken;
  "auth/shared/getValidSession": typeof auth_shared_getValidSession;
  "auth/shared/rateLimitWindowMs": typeof auth_shared_rateLimitWindowMs;
  "auth/shared/requireAuth": typeof auth_shared_requireAuth;
  "auth/shared/sessionDurations": typeof auth_shared_sessionDurations;
  "costTracking/actions/internalCheckBudgetAlert": typeof costTracking_actions_internalCheckBudgetAlert;
  "costTracking/mutations/internalMarkBudgetAlertSent": typeof costTracking_mutations_internalMarkBudgetAlertSent;
  "costTracking/queries/getCostByProvider": typeof costTracking_queries_getCostByProvider;
  "costTracking/queries/getCostHistory": typeof costTracking_queries_getCostHistory;
  "costTracking/queries/getMonthlyCost": typeof costTracking_queries_getMonthlyCost;
  "costTracking/queries/internalCheckBudgetReached": typeof costTracking_queries_internalCheckBudgetReached;
  "costTracking/queries/internalGetMonthlyCost": typeof costTracking_queries_internalGetMonthlyCost;
  "costTracking/shared/assertWithinBudget": typeof costTracking_shared_assertWithinBudget;
  "costTracking/shared/budgetReachedMessage": typeof costTracking_shared_budgetReachedMessage;
  "costTracking/shared/computeMonthlyCost": typeof costTracking_shared_computeMonthlyCost;
  "costTracking/shared/getBudgetThreshold": typeof costTracking_shared_getBudgetThreshold;
  "costTracking/shared/isMonthlyBudgetReached": typeof costTracking_shared_isMonthlyBudgetReached;
  crons: typeof crons;
  customFields: typeof customFields;
  "dashboard/queries/activeJobsCount": typeof dashboard_queries_activeJobsCount;
  "dashboard/queries/monthlySpend": typeof dashboard_queries_monthlySpend;
  "dashboard/queries/recentResearch": typeof dashboard_queries_recentResearch;
  "dashboard/queries/upcomingSchedules": typeof dashboard_queries_upcomingSchedules;
  "earnings/actions/internalCheckEarningsTriggers": typeof earnings_actions_internalCheckEarningsTriggers;
  "earnings/actions/internalFetchAllEarnings": typeof earnings_actions_internalFetchAllEarnings;
  "earnings/actions/internalTestCheckEarningsTriggers": typeof earnings_actions_internalTestCheckEarningsTriggers;
  "earnings/mutations/internalRecordTriggeredRun": typeof earnings_mutations_internalRecordTriggeredRun;
  "earnings/mutations/internalUpdateScheduleLastRunAt": typeof earnings_mutations_internalUpdateScheduleLastRunAt;
  "earnings/mutations/internalUpsertEarnings": typeof earnings_mutations_internalUpsertEarnings;
  "earnings/queries/getEarningsByStockId": typeof earnings_queries_getEarningsByStockId;
  "earnings/queries/getEarningsSummaryAll": typeof earnings_queries_getEarningsSummaryAll;
  "earnings/queries/internalCheckAlreadyTriggered": typeof earnings_queries_internalCheckAlreadyTriggered;
  "earnings/queries/internalCheckAlreadyTriggeredForQuarter": typeof earnings_queries_internalCheckAlreadyTriggeredForQuarter;
  "earnings/queries/internalGetEarningsByDate": typeof earnings_queries_internalGetEarningsByDate;
  "earnings/queries/internalGetEarningsForStocks": typeof earnings_queries_internalGetEarningsForStocks;
  "earnings/queries/internalGetEarningsSchedules": typeof earnings_queries_internalGetEarningsSchedules;
  "earnings/queries/internalGetStocksByIds": typeof earnings_queries_internalGetStocksByIds;
  "earnings/queries/internalListAllStocks": typeof earnings_queries_internalListAllStocks;
  "earnings/shared/addDays": typeof earnings_shared_addDays;
  "earnings/shared/formatDate": typeof earnings_shared_formatDate;
  "earnings/shared/getCurrentReportingQuarter": typeof earnings_shared_getCurrentReportingQuarter;
  "earnings/shared/getQuarterKey": typeof earnings_shared_getQuarterKey;
  "earnings/shared/getTodayInTimezone": typeof earnings_shared_getTodayInTimezone;
  "earnings/shared/handleAggregateMode": typeof earnings_shared_handleAggregateMode;
  "earnings/shared/handleEachMode": typeof earnings_shared_handleEachMode;
  "earnings/shared/resolveEligibleStocks": typeof earnings_shared_resolveEligibleStocks;
  "earnings/shared/resolveSelectedStocks": typeof earnings_shared_resolveSelectedStocks;
  "earnings/shared/sleepMs": typeof earnings_shared_sleepMs;
  http: typeof http;
  "lib/anthropicBatchHelpers": typeof lib_anthropicBatchHelpers;
  "lib/asyncIterators": typeof lib_asyncIterators;
  "lib/exchangeTimezones": typeof lib_exchangeTimezones;
  "lib/finnhub/isEligibleType": typeof lib_finnhub_isEligibleType;
  "lib/finnhub/mapExchange": typeof lib_finnhub_mapExchange;
  "lib/finnhub/rankSearchResults": typeof lib_finnhub_rankSearchResults;
  "lib/finnhub/sortRank": typeof lib_finnhub_sortRank;
  "lib/finnhub/types": typeof lib_finnhub_types;
  "lib/logger": typeof lib_logger;
  "notifications/actions/detectTelegramChatId": typeof notifications_actions_detectTelegramChatId;
  "notifications/actions/internalDispatchBatchNotification": typeof notifications_actions_internalDispatchBatchNotification;
  "notifications/actions/internalDispatchJobNotification": typeof notifications_actions_internalDispatchJobNotification;
  "notifications/actions/internalSendEmail": typeof notifications_actions_internalSendEmail;
  "notifications/actions/internalSendTelegramMessage": typeof notifications_actions_internalSendTelegramMessage;
  "notifications/actions/sendTestEmail": typeof notifications_actions_sendTestEmail;
  "notifications/actions/sendTestTelegram": typeof notifications_actions_sendTestTelegram;
  "notifications/shared/buildResearchEmailHtml": typeof notifications_shared_buildResearchEmailHtml;
  "notifications/shared/escapeHtml": typeof notifications_shared_escapeHtml;
  "notifications/shared/formatDuration": typeof notifications_shared_formatDuration;
  "notifications/shared/sanitizeForTelegramMarkdown": typeof notifications_shared_sanitizeForTelegramMarkdown;
  "prompts/mutations/clonePrompt": typeof prompts_mutations_clonePrompt;
  "prompts/mutations/createPrompt": typeof prompts_mutations_createPrompt;
  "prompts/mutations/deletePrompt": typeof prompts_mutations_deletePrompt;
  "prompts/mutations/updatePrompt": typeof prompts_mutations_updatePrompt;
  "prompts/queries/getPrompt": typeof prompts_queries_getPrompt;
  "prompts/queries/internalGetPrompt": typeof prompts_queries_internalGetPrompt;
  "prompts/queries/listPrompts": typeof prompts_queries_listPrompts;
  "prompts/shared/promptType": typeof prompts_shared_promptType;
  "providers/anthropic": typeof providers_anthropic;
  "providers/anthropicManagedAgents": typeof providers_anthropicManagedAgents;
  "providers/anthropicManagedAgents/basename": typeof providers_anthropicManagedAgents_basename;
  "providers/anthropicManagedAgents/collectCompletedResult": typeof providers_anthropicManagedAgents_collectCompletedResult;
  "providers/anthropicManagedAgents/downloadReportFile": typeof providers_anthropicManagedAgents_downloadReportFile;
  "providers/anthropicManagedAgents/isMarkdown": typeof providers_anthropicManagedAgents_isMarkdown;
  "providers/anthropicManagedAgents/pickReportFile": typeof providers_anthropicManagedAgents_pickReportFile;
  "providers/anthropicManagedAgents/resolveIdleSession": typeof providers_anthropicManagedAgents_resolveIdleSession;
  "providers/anthropicModelLimits": typeof providers_anthropicModelLimits;
  "providers/constants": typeof providers_constants;
  "providers/formatOpenaiAdapter": typeof providers_formatOpenaiAdapter;
  "providers/index": typeof providers_index;
  "providers/managedAgentProvisioning/agentName": typeof providers_managedAgentProvisioning_agentName;
  "providers/managedAgentProvisioning/buildCoordinatorSystemPrompt": typeof providers_managedAgentProvisioning_buildCoordinatorSystemPrompt;
  "providers/managedAgentProvisioning/buildToolset": typeof providers_managedAgentProvisioning_buildToolset;
  "providers/managedAgentProvisioning/ensureAgent": typeof providers_managedAgentProvisioning_ensureAgent;
  "providers/managedAgentProvisioning/ensureEnvironment": typeof providers_managedAgentProvisioning_ensureEnvironment;
  "providers/managedAgentProvisioning/ensureManagedAgentResources": typeof providers_managedAgentProvisioning_ensureManagedAgentResources;
  "providers/managedAgentProvisioning/findAgentByName": typeof providers_managedAgentProvisioning_findAgentByName;
  "providers/managedAgentProvisioning/hashParams": typeof providers_managedAgentProvisioning_hashParams;
  "providers/openai": typeof providers_openai;
  "providers/openai/buildOpenAIResponseCreateParams": typeof providers_openai_buildOpenAIResponseCreateParams;
  "providers/openai/estimateOpenAICost": typeof providers_openai_estimateOpenAICost;
  "providers/openai/renderOutputTextWithCitations": typeof providers_openai_renderOutputTextWithCitations;
  "providers/openai/renderResearchMarkdown": typeof providers_openai_renderResearchMarkdown;
  "providers/openaiResponses": typeof providers_openaiResponses;
  "providers/types": typeof providers_types;
  "research/actions/checkJobHealth": typeof research_actions_checkJobHealth;
  "research/actions/internalPollFormat": typeof research_actions_internalPollFormat;
  "research/actions/internalPollJob": typeof research_actions_internalPollJob;
  "research/actions/internalProcessWebhookEvent": typeof research_actions_internalProcessWebhookEvent;
  "research/actions/internalRecoverStaleFormatting": typeof research_actions_internalRecoverStaleFormatting;
  "research/actions/internalRecoverStaleJobs": typeof research_actions_internalRecoverStaleJobs;
  "research/actions/internalReformatByTicker": typeof research_actions_internalReformatByTicker;
  "research/actions/internalReformatResearchJob": typeof research_actions_internalReformatResearchJob;
  "research/actions/internalStartFormat": typeof research_actions_internalStartFormat;
  "research/actions/internalStartResearch": typeof research_actions_internalStartResearch;
  "research/mutations/cancelJob": typeof research_mutations_cancelJob;
  "research/mutations/createAndStartResearch": typeof research_mutations_createAndStartResearch;
  "research/mutations/createResearchJob": typeof research_mutations_createResearchJob;
  "research/mutations/deleteJob": typeof research_mutations_deleteJob;
  "research/mutations/internalApplyReformattedResult": typeof research_mutations_internalApplyReformattedResult;
  "research/mutations/internalBeginBackfillFormat": typeof research_mutations_internalBeginBackfillFormat;
  "research/mutations/internalBeginFormattingPhase": typeof research_mutations_internalBeginFormattingPhase;
  "research/mutations/internalClearFormatExternalId": typeof research_mutations_internalClearFormatExternalId;
  "research/mutations/internalCompleteFormattedJob": typeof research_mutations_internalCompleteFormattedJob;
  "research/mutations/internalDrainProviderQueue": typeof research_mutations_internalDrainProviderQueue;
  "research/mutations/internalIncrementAttempts": typeof research_mutations_internalIncrementAttempts;
  "research/mutations/internalIncrementFormatAttempts": typeof research_mutations_internalIncrementFormatAttempts;
  "research/mutations/internalLogCost": typeof research_mutations_internalLogCost;
  "research/mutations/internalSetFormatExternalId": typeof research_mutations_internalSetFormatExternalId;
  "research/mutations/internalUpdateJobStatus": typeof research_mutations_internalUpdateJobStatus;
  "research/mutations/retryJob": typeof research_mutations_retryJob;
  "research/mutations/toggleFavorite": typeof research_mutations_toggleFavorite;
  "research/queries/getActiveJobs": typeof research_queries_getActiveJobs;
  "research/queries/getJob": typeof research_queries_getJob;
  "research/queries/internalDebugJobFormatting": typeof research_queries_internalDebugJobFormatting;
  "research/queries/internalDebugListRecentJobs": typeof research_queries_internalDebugListRecentJobs;
  "research/queries/internalFindLatestCompletedJobByTicker": typeof research_queries_internalFindLatestCompletedJobByTicker;
  "research/queries/internalGetConcurrencyJobs": typeof research_queries_internalGetConcurrencyJobs;
  "research/queries/internalGetJob": typeof research_queries_internalGetJob;
  "research/queries/internalGetJobByExternalId": typeof research_queries_internalGetJobByExternalId;
  "research/queries/internalGetJobByFormatExternalId": typeof research_queries_internalGetJobByFormatExternalId;
  "research/queries/internalGetStaleFormattingJobs": typeof research_queries_internalGetStaleFormattingJobs;
  "research/queries/internalGetStaleRunningJobs": typeof research_queries_internalGetStaleRunningJobs;
  "research/queries/internalGetStock": typeof research_queries_internalGetStock;
  "research/queries/internalSummarizeResearchResultSizes": typeof research_queries_internalSummarizeResearchResultSizes;
  "research/queries/listFavorites": typeof research_queries_listFavorites;
  "research/queries/listJobs": typeof research_queries_listJobs;
  "research/queries/listResults": typeof research_queries_listResults;
  "research/queries/searchResults": typeof research_queries_searchResults;
  "research/shared/applyCompletedResult": typeof research_shared_applyCompletedResult;
  "research/shared/applyFailedResult": typeof research_shared_applyFailedResult;
  "research/shared/clearFormatTrackingFields": typeof research_shared_clearFormatTrackingFields;
  "research/shared/completeFormatJob": typeof research_shared_completeFormatJob;
  "research/shared/countH2": typeof research_shared_countH2;
  "research/shared/countH3": typeof research_shared_countH3;
  "research/shared/dispatchPostCompleteSideEffects": typeof research_shared_dispatchPostCompleteSideEffects;
  "research/shared/formatMode": typeof research_shared_formatMode;
  "research/shared/formatPollInitialDelayMs": typeof research_shared_formatPollInitialDelayMs;
  "research/shared/getOpenAIApiKey": typeof research_shared_getOpenAIApiKey;
  "research/shared/getProviderApiKey": typeof research_shared_getProviderApiKey;
  "research/shared/handleFormatTimeout": typeof research_shared_handleFormatTimeout;
  "research/shared/handlePollCompleted": typeof research_shared_handlePollCompleted;
  "research/shared/handleStartError": typeof research_shared_handleStartError;
  "research/shared/isPipelineJob": typeof research_shared_isPipelineJob;
  "research/shared/isTerminal": typeof research_shared_isTerminal;
  "research/shared/jobHardTimeoutMs": typeof research_shared_jobHardTimeoutMs;
  "research/shared/jobStatus": typeof research_shared_jobStatus;
  "research/shared/loadActiveJobsForConcurrency": typeof research_shared_loadActiveJobsForConcurrency;
  "research/shared/loadDisplayActiveJobs": typeof research_shared_loadDisplayActiveJobs;
  "research/shared/loadFormattingJobs": typeof research_shared_loadFormattingJobs;
  "research/shared/loadJob": typeof research_shared_loadJob;
  "research/shared/loadJobForBackfill": typeof research_shared_loadJobForBackfill;
  "research/shared/maxRetries": typeof research_shared_maxRetries;
  "research/shared/maybeTimeoutOrReschedule": typeof research_shared_maybeTimeoutOrReschedule;
  "research/shared/missingKeyMessage": typeof research_shared_missingKeyMessage;
  "research/shared/parseRetryDelayMs": typeof research_shared_parseRetryDelayMs;
  "research/shared/reformatStarted": typeof research_shared_reformatStarted;
  "research/shared/resolvePrompt": typeof research_shared_resolvePrompt;
  "research/shared/schedulePoll": typeof research_shared_schedulePoll;
  "research/shared/scheduleProviderQueueDrain": typeof research_shared_scheduleProviderQueueDrain;
  "research/shared/scheduleStart": typeof research_shared_scheduleStart;
  "research/shared/sleep": typeof research_shared_sleep;
  "research/shared/sourceMarkdown": typeof research_shared_sourceMarkdown;
  "research/shared/statusMessage": typeof research_shared_statusMessage;
  researchConcurrency: typeof researchConcurrency;
  researchFormatCore: typeof researchFormatCore;
  researchFormatPrepass: typeof researchFormatPrepass;
  researchJobSearchMetadata: typeof researchJobSearchMetadata;
  "schedules/actions/internalExecuteRunNow": typeof schedules_actions_internalExecuteRunNow;
  "schedules/actions/internalExecuteScheduledRun": typeof schedules_actions_internalExecuteScheduledRun;
  "schedules/actions/internalScheduleNextRun": typeof schedules_actions_internalScheduleNextRun;
  "schedules/mutations/createSchedule": typeof schedules_mutations_createSchedule;
  "schedules/mutations/deleteSchedule": typeof schedules_mutations_deleteSchedule;
  "schedules/mutations/internalCreateScheduledJob": typeof schedules_mutations_internalCreateScheduledJob;
  "schedules/mutations/internalUpdateScheduleNextRun": typeof schedules_mutations_internalUpdateScheduleNextRun;
  "schedules/mutations/runScheduleNow": typeof schedules_mutations_runScheduleNow;
  "schedules/mutations/toggleGlobalPause": typeof schedules_mutations_toggleGlobalPause;
  "schedules/mutations/toggleSchedule": typeof schedules_mutations_toggleSchedule;
  "schedules/mutations/updateSchedule": typeof schedules_mutations_updateSchedule;
  "schedules/queries/getGlobalPauseStatus": typeof schedules_queries_getGlobalPauseStatus;
  "schedules/queries/getSchedule": typeof schedules_queries_getSchedule;
  "schedules/queries/getScheduleHistory": typeof schedules_queries_getScheduleHistory;
  "schedules/queries/getUpcomingRuns": typeof schedules_queries_getUpcomingRuns;
  "schedules/queries/internalGetGlobalPauseStatus": typeof schedules_queries_internalGetGlobalPauseStatus;
  "schedules/queries/internalGetSchedule": typeof schedules_queries_internalGetSchedule;
  "schedules/queries/internalListStocks": typeof schedules_queries_internalListStocks;
  "schedules/queries/listSchedules": typeof schedules_queries_listSchedules;
  "schedules/shared/computeNextRunAt": typeof schedules_shared_computeNextRunAt;
  "schedules/shared/earningsConfigValidator": typeof schedules_shared_earningsConfigValidator;
  "schedules/shared/getDatePartsInTimezone": typeof schedules_shared_getDatePartsInTimezone;
  "schedules/shared/getUtcTimestampFromTzParts": typeof schedules_shared_getUtcTimestampFromTzParts;
  "schedules/shared/matchesField": typeof schedules_shared_matchesField;
  "schedules/shared/parseCron": typeof schedules_shared_parseCron;
  "schedules/shared/parseField": typeof schedules_shared_parseField;
  "schedules/shared/stockSelectionValidator": typeof schedules_shared_stockSelectionValidator;
  "seed/mutations/internalBackfillCostLogs": typeof seed_mutations_internalBackfillCostLogs;
  "seed/mutations/internalSeedPrompts": typeof seed_mutations_internalSeedPrompts;
  "settings/mutations/upsertSetting": typeof settings_mutations_upsertSetting;
  "settings/queries/getSetting": typeof settings_queries_getSetting;
  "settings/shared/protectedSettingKeys": typeof settings_shared_protectedSettingKeys;
  "stocks/actions/resolveStockSymbol": typeof stocks_actions_resolveStockSymbol;
  "stocks/actions/searchStockSymbols": typeof stocks_actions_searchStockSymbols;
  "stocks/mutations/addStock": typeof stocks_mutations_addStock;
  "stocks/mutations/deleteStock": typeof stocks_mutations_deleteStock;
  "stocks/mutations/updateStock": typeof stocks_mutations_updateStock;
  "stocks/queries/getStock": typeof stocks_queries_getStock;
  "stocks/queries/getStockByTicker": typeof stocks_queries_getStockByTicker;
  "stocks/queries/listStocks": typeof stocks_queries_listStocks;
  "stocks/queries/listTags": typeof stocks_queries_listTags;
  "stocks/shared/getFinnhubApiKey": typeof stocks_shared_getFinnhubApiKey;
  "stocks/shared/maxQueryLength": typeof stocks_shared_maxQueryLength;
  "stocks/shared/minQueryLength": typeof stocks_shared_minQueryLength;
  "stocks/shared/normalizeLookupQuery": typeof stocks_shared_normalizeLookupQuery;
  "stocks/shared/requireValidSession": typeof stocks_shared_requireValidSession;
  validation: typeof validation;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
