/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as auditLog from "../auditLog.js";
import type * as auth_actions_changePassword from "../auth/actions/changePassword.js";
import type * as auth_actions_login from "../auth/actions/login.js";
import type * as auth_actions_logout from "../auth/actions/logout.js";
import type * as auth_mutations_createSession from "../auth/mutations/createSession.js";
import type * as auth_mutations_deleteSession from "../auth/mutations/deleteSession.js";
import type * as auth_mutations_recordLoginAttempt from "../auth/mutations/recordLoginAttempt.js";
import type * as auth_mutations_refreshSession from "../auth/mutations/refreshSession.js";
import type * as auth_mutations_upsertSettingInternal from "../auth/mutations/upsertSettingInternal.js";
import type * as auth_queries_checkLoginRateLimit from "../auth/queries/checkLoginRateLimit.js";
import type * as auth_queries_getSettingValue from "../auth/queries/getSettingValue.js";
import type * as auth_queries_validateSession from "../auth/queries/validateSession.js";
import type * as auth_queries_validateSessionInternal from "../auth/queries/validateSessionInternal.js";
import type * as auth_shared_computeLoginRateLimit from "../auth/shared/computeLoginRateLimit.js";
import type * as auth_shared_generateToken from "../auth/shared/generateToken.js";
import type * as auth_shared_getValidSession from "../auth/shared/getValidSession.js";
import type * as auth_shared_rateLimitWindowMs from "../auth/shared/rateLimitWindowMs.js";
import type * as auth_shared_requireAuth from "../auth/shared/requireAuth.js";
import type * as auth_shared_sessionDurations from "../auth/shared/sessionDurations.js";
import type * as budgetAlert from "../budgetAlert.js";
import type * as costTracking_mutations_markBudgetAlertSent from "../costTracking/mutations/markBudgetAlertSent.js";
import type * as costTracking_queries_checkBudgetReachedInternal from "../costTracking/queries/checkBudgetReachedInternal.js";
import type * as costTracking_queries_getCostByProvider from "../costTracking/queries/getCostByProvider.js";
import type * as costTracking_queries_getCostHistory from "../costTracking/queries/getCostHistory.js";
import type * as costTracking_queries_getMonthlyCost from "../costTracking/queries/getMonthlyCost.js";
import type * as costTracking_queries_getMonthlyCostInternal from "../costTracking/queries/getMonthlyCostInternal.js";
import type * as costTracking_shared_assertWithinBudget from "../costTracking/shared/assertWithinBudget.js";
import type * as costTracking_shared_budgetReachedMessage from "../costTracking/shared/budgetReachedMessage.js";
import type * as costTracking_shared_computeMonthlyCost from "../costTracking/shared/computeMonthlyCost.js";
import type * as costTracking_shared_getBudgetThreshold from "../costTracking/shared/getBudgetThreshold.js";
import type * as costTracking_shared_isMonthlyBudgetReached from "../costTracking/shared/isMonthlyBudgetReached.js";
import type * as crons from "../crons.js";
import type * as dashboard_queries_activeJobsCount from "../dashboard/queries/activeJobsCount.js";
import type * as dashboard_queries_monthlySpend from "../dashboard/queries/monthlySpend.js";
import type * as dashboard_queries_recentResearch from "../dashboard/queries/recentResearch.js";
import type * as dashboard_queries_upcomingSchedules from "../dashboard/queries/upcomingSchedules.js";
import type * as earnings_actions_checkEarningsTriggers from "../earnings/actions/checkEarningsTriggers.js";
import type * as earnings_actions_fetchAllEarnings from "../earnings/actions/fetchAllEarnings.js";
import type * as earnings_actions_testCheckEarningsTriggers from "../earnings/actions/testCheckEarningsTriggers.js";
import type * as earnings_mutations_recordTriggeredRun from "../earnings/mutations/recordTriggeredRun.js";
import type * as earnings_mutations_updateScheduleLastRunAt from "../earnings/mutations/updateScheduleLastRunAt.js";
import type * as earnings_mutations_upsertEarnings from "../earnings/mutations/upsertEarnings.js";
import type * as earnings_queries_checkAlreadyTriggered from "../earnings/queries/checkAlreadyTriggered.js";
import type * as earnings_queries_checkAlreadyTriggeredForQuarter from "../earnings/queries/checkAlreadyTriggeredForQuarter.js";
import type * as earnings_queries_getEarningsByDate from "../earnings/queries/getEarningsByDate.js";
import type * as earnings_queries_getEarningsByStockId from "../earnings/queries/getEarningsByStockId.js";
import type * as earnings_queries_getEarningsForStocks from "../earnings/queries/getEarningsForStocks.js";
import type * as earnings_queries_getEarningsSchedules from "../earnings/queries/getEarningsSchedules.js";
import type * as earnings_queries_getEarningsSummaryAll from "../earnings/queries/getEarningsSummaryAll.js";
import type * as earnings_queries_getStocksByIds from "../earnings/queries/getStocksByIds.js";
import type * as earnings_queries_listAllStocksInternal from "../earnings/queries/listAllStocksInternal.js";
import type * as earnings_shared_addDays from "../earnings/shared/addDays.js";
import type * as earnings_shared_formatDate from "../earnings/shared/formatDate.js";
import type * as earnings_shared_getCurrentReportingQuarter from "../earnings/shared/getCurrentReportingQuarter.js";
import type * as earnings_shared_getQuarterKey from "../earnings/shared/getQuarterKey.js";
import type * as earnings_shared_getTodayInTimezone from "../earnings/shared/getTodayInTimezone.js";
import type * as earnings_shared_handleAggregateMode from "../earnings/shared/handleAggregateMode.js";
import type * as earnings_shared_handleEachMode from "../earnings/shared/handleEachMode.js";
import type * as earnings_shared_resolveEligibleStocks from "../earnings/shared/resolveEligibleStocks.js";
import type * as earnings_shared_resolveSelectedStocks from "../earnings/shared/resolveSelectedStocks.js";
import type * as earnings_shared_sleepMs from "../earnings/shared/sleepMs.js";
import type * as http from "../http.js";
import type * as lib_anthropicBatchHelpers from "../lib/anthropicBatchHelpers.js";
import type * as lib_asyncIterators from "../lib/asyncIterators.js";
import type * as lib_exchangeTimezones from "../lib/exchangeTimezones.js";
import type * as lib_finnhub_isEligibleType from "../lib/finnhub/isEligibleType.js";
import type * as lib_finnhub_mapExchange from "../lib/finnhub/mapExchange.js";
import type * as lib_finnhub_rankSearchResults from "../lib/finnhub/rankSearchResults.js";
import type * as lib_finnhub_sortRank from "../lib/finnhub/sortRank.js";
import type * as lib_finnhub_types from "../lib/finnhub/types.js";
import type * as lib_logger from "../lib/logger.js";
import type * as notifications_actions_detectTelegramChatId from "../notifications/actions/detectTelegramChatId.js";
import type * as notifications_actions_dispatchBatchNotification from "../notifications/actions/dispatchBatchNotification.js";
import type * as notifications_actions_dispatchJobNotification from "../notifications/actions/dispatchJobNotification.js";
import type * as notifications_actions_sendEmail from "../notifications/actions/sendEmail.js";
import type * as notifications_actions_sendTelegramMessage from "../notifications/actions/sendTelegramMessage.js";
import type * as notifications_actions_sendTestEmail from "../notifications/actions/sendTestEmail.js";
import type * as notifications_actions_sendTestTelegram from "../notifications/actions/sendTestTelegram.js";
import type * as notifications_shared_buildResearchEmailHtml from "../notifications/shared/buildResearchEmailHtml.js";
import type * as notifications_shared_escapeHtml from "../notifications/shared/escapeHtml.js";
import type * as notifications_shared_formatDuration from "../notifications/shared/formatDuration.js";
import type * as notifications_shared_sanitizeForTelegramMarkdown from "../notifications/shared/sanitizeForTelegramMarkdown.js";
import type * as prompts_mutations_clonePrompt from "../prompts/mutations/clonePrompt.js";
import type * as prompts_mutations_createPrompt from "../prompts/mutations/createPrompt.js";
import type * as prompts_mutations_deletePrompt from "../prompts/mutations/deletePrompt.js";
import type * as prompts_mutations_updatePrompt from "../prompts/mutations/updatePrompt.js";
import type * as prompts_queries_getPrompt from "../prompts/queries/getPrompt.js";
import type * as prompts_queries_getPromptInternal from "../prompts/queries/getPromptInternal.js";
import type * as prompts_queries_listPrompts from "../prompts/queries/listPrompts.js";
import type * as prompts_shared_promptType from "../prompts/shared/promptType.js";
import type * as providers_anthropic from "../providers/anthropic.js";
import type * as providers_anthropicManagedAgents from "../providers/anthropicManagedAgents.js";
import type * as providers_anthropicManagedAgents_collectCompletedResult from "../providers/anthropicManagedAgents/collectCompletedResult.js";
import type * as providers_anthropicManagedAgents_pickReportFile from "../providers/anthropicManagedAgents/pickReportFile.js";
import type * as providers_anthropicManagedAgents_resolveIdleSession from "../providers/anthropicManagedAgents/resolveIdleSession.js";
import type * as providers_anthropicModelLimits from "../providers/anthropicModelLimits.js";
import type * as providers_constants from "../providers/constants.js";
import type * as providers_formatOpenaiAdapter from "../providers/formatOpenaiAdapter.js";
import type * as providers_index from "../providers/index.js";
import type * as providers_managedAgentProvisioning_agentName from "../providers/managedAgentProvisioning/agentName.js";
import type * as providers_managedAgentProvisioning_buildCoordinatorSystemPrompt from "../providers/managedAgentProvisioning/buildCoordinatorSystemPrompt.js";
import type * as providers_managedAgentProvisioning_buildToolset from "../providers/managedAgentProvisioning/buildToolset.js";
import type * as providers_managedAgentProvisioning_ensureAgent from "../providers/managedAgentProvisioning/ensureAgent.js";
import type * as providers_managedAgentProvisioning_ensureEnvironment from "../providers/managedAgentProvisioning/ensureEnvironment.js";
import type * as providers_managedAgentProvisioning_ensureManagedAgentResources from "../providers/managedAgentProvisioning/ensureManagedAgentResources.js";
import type * as providers_managedAgentProvisioning_findAgentByName from "../providers/managedAgentProvisioning/findAgentByName.js";
import type * as providers_managedAgentProvisioning_hashParams from "../providers/managedAgentProvisioning/hashParams.js";
import type * as providers_openai from "../providers/openai.js";
import type * as providers_openai_buildOpenAIResponseCreateParams from "../providers/openai/buildOpenAIResponseCreateParams.js";
import type * as providers_openai_estimateOpenAICost from "../providers/openai/estimateOpenAICost.js";
import type * as providers_openai_renderOutputTextWithCitations from "../providers/openai/renderOutputTextWithCitations.js";
import type * as providers_openai_renderResearchMarkdown from "../providers/openai/renderResearchMarkdown.js";
import type * as providers_openaiResponses from "../providers/openaiResponses.js";
import type * as providers_types from "../providers/types.js";
import type * as research_actions_checkJobHealth from "../research/actions/checkJobHealth.js";
import type * as research_actions_pollFormat from "../research/actions/pollFormat.js";
import type * as research_actions_pollJob from "../research/actions/pollJob.js";
import type * as research_actions_processWebhookEvent from "../research/actions/processWebhookEvent.js";
import type * as research_actions_recoverStaleFormatting from "../research/actions/recoverStaleFormatting.js";
import type * as research_actions_recoverStaleJobs from "../research/actions/recoverStaleJobs.js";
import type * as research_actions_reformatByTicker from "../research/actions/reformatByTicker.js";
import type * as research_actions_reformatResearchJob from "../research/actions/reformatResearchJob.js";
import type * as research_actions_startFormat from "../research/actions/startFormat.js";
import type * as research_actions_startResearch from "../research/actions/startResearch.js";
import type * as research_mutations_applyReformattedResult from "../research/mutations/applyReformattedResult.js";
import type * as research_mutations_beginBackfillFormat from "../research/mutations/beginBackfillFormat.js";
import type * as research_mutations_beginFormattingPhase from "../research/mutations/beginFormattingPhase.js";
import type * as research_mutations_cancelJob from "../research/mutations/cancelJob.js";
import type * as research_mutations_clearFormatExternalId from "../research/mutations/clearFormatExternalId.js";
import type * as research_mutations_completeFormattedJob from "../research/mutations/completeFormattedJob.js";
import type * as research_mutations_createAndStartResearch from "../research/mutations/createAndStartResearch.js";
import type * as research_mutations_createResearchJob from "../research/mutations/createResearchJob.js";
import type * as research_mutations_deleteJob from "../research/mutations/deleteJob.js";
import type * as research_mutations_drainProviderQueue from "../research/mutations/drainProviderQueue.js";
import type * as research_mutations_incrementAttempts from "../research/mutations/incrementAttempts.js";
import type * as research_mutations_incrementFormatAttempts from "../research/mutations/incrementFormatAttempts.js";
import type * as research_mutations_logCost from "../research/mutations/logCost.js";
import type * as research_mutations_retryJob from "../research/mutations/retryJob.js";
import type * as research_mutations_setFormatExternalId from "../research/mutations/setFormatExternalId.js";
import type * as research_mutations_toggleFavorite from "../research/mutations/toggleFavorite.js";
import type * as research_mutations_updateJobStatus from "../research/mutations/updateJobStatus.js";
import type * as research_queries_debugJobFormatting from "../research/queries/debugJobFormatting.js";
import type * as research_queries_debugListRecentJobs from "../research/queries/debugListRecentJobs.js";
import type * as research_queries_findLatestCompletedJobByTicker from "../research/queries/findLatestCompletedJobByTicker.js";
import type * as research_queries_getActiveJobs from "../research/queries/getActiveJobs.js";
import type * as research_queries_getConcurrencyJobsInternal from "../research/queries/getConcurrencyJobsInternal.js";
import type * as research_queries_getJob from "../research/queries/getJob.js";
import type * as research_queries_getJobByExternalId from "../research/queries/getJobByExternalId.js";
import type * as research_queries_getJobByFormatExternalId from "../research/queries/getJobByFormatExternalId.js";
import type * as research_queries_getJobInternal from "../research/queries/getJobInternal.js";
import type * as research_queries_getStaleFormattingJobs from "../research/queries/getStaleFormattingJobs.js";
import type * as research_queries_getStaleRunningJobs from "../research/queries/getStaleRunningJobs.js";
import type * as research_queries_getStockInternal from "../research/queries/getStockInternal.js";
import type * as research_queries_listFavorites from "../research/queries/listFavorites.js";
import type * as research_queries_listJobs from "../research/queries/listJobs.js";
import type * as research_queries_listResults from "../research/queries/listResults.js";
import type * as research_queries_searchResults from "../research/queries/searchResults.js";
import type * as research_queries_summarizeResearchResultSizes from "../research/queries/summarizeResearchResultSizes.js";
import type * as research_shared_applyCompletedResult from "../research/shared/applyCompletedResult.js";
import type * as research_shared_applyFailedResult from "../research/shared/applyFailedResult.js";
import type * as research_shared_clearFormatTrackingFields from "../research/shared/clearFormatTrackingFields.js";
import type * as research_shared_completeFormatJob from "../research/shared/completeFormatJob.js";
import type * as research_shared_countH2 from "../research/shared/countH2.js";
import type * as research_shared_countH3 from "../research/shared/countH3.js";
import type * as research_shared_dispatchPostCompleteSideEffects from "../research/shared/dispatchPostCompleteSideEffects.js";
import type * as research_shared_formatMode from "../research/shared/formatMode.js";
import type * as research_shared_formatPollInitialDelayMs from "../research/shared/formatPollInitialDelayMs.js";
import type * as research_shared_getOpenAIApiKey from "../research/shared/getOpenAIApiKey.js";
import type * as research_shared_getProviderApiKey from "../research/shared/getProviderApiKey.js";
import type * as research_shared_handleFormatTimeout from "../research/shared/handleFormatTimeout.js";
import type * as research_shared_handlePollCompleted from "../research/shared/handlePollCompleted.js";
import type * as research_shared_handleStartError from "../research/shared/handleStartError.js";
import type * as research_shared_isPipelineJob from "../research/shared/isPipelineJob.js";
import type * as research_shared_isTerminal from "../research/shared/isTerminal.js";
import type * as research_shared_jobHardTimeoutMs from "../research/shared/jobHardTimeoutMs.js";
import type * as research_shared_jobStatus from "../research/shared/jobStatus.js";
import type * as research_shared_loadActiveJobsForConcurrency from "../research/shared/loadActiveJobsForConcurrency.js";
import type * as research_shared_loadDisplayActiveJobs from "../research/shared/loadDisplayActiveJobs.js";
import type * as research_shared_loadFormattingJobs from "../research/shared/loadFormattingJobs.js";
import type * as research_shared_loadJob from "../research/shared/loadJob.js";
import type * as research_shared_loadJobForBackfill from "../research/shared/loadJobForBackfill.js";
import type * as research_shared_maxRetries from "../research/shared/maxRetries.js";
import type * as research_shared_maybeTimeoutOrReschedule from "../research/shared/maybeTimeoutOrReschedule.js";
import type * as research_shared_missingKeyMessage from "../research/shared/missingKeyMessage.js";
import type * as research_shared_parseRetryDelayMs from "../research/shared/parseRetryDelayMs.js";
import type * as research_shared_reformatStarted from "../research/shared/reformatStarted.js";
import type * as research_shared_resolvePrompt from "../research/shared/resolvePrompt.js";
import type * as research_shared_schedulePoll from "../research/shared/schedulePoll.js";
import type * as research_shared_scheduleProviderQueueDrain from "../research/shared/scheduleProviderQueueDrain.js";
import type * as research_shared_scheduleStart from "../research/shared/scheduleStart.js";
import type * as research_shared_sleep from "../research/shared/sleep.js";
import type * as research_shared_sourceMarkdown from "../research/shared/sourceMarkdown.js";
import type * as research_shared_statusMessage from "../research/shared/statusMessage.js";
import type * as researchConcurrency from "../researchConcurrency.js";
import type * as researchFormatCore from "../researchFormatCore.js";
import type * as researchFormatPrepass from "../researchFormatPrepass.js";
import type * as researchJobSearchMetadata from "../researchJobSearchMetadata.js";
import type * as schedules_actions_executeRunNow from "../schedules/actions/executeRunNow.js";
import type * as schedules_actions_executeScheduledRun from "../schedules/actions/executeScheduledRun.js";
import type * as schedules_actions_scheduleNextRun from "../schedules/actions/scheduleNextRun.js";
import type * as schedules_mutations_createSchedule from "../schedules/mutations/createSchedule.js";
import type * as schedules_mutations_createScheduledJob from "../schedules/mutations/createScheduledJob.js";
import type * as schedules_mutations_deleteSchedule from "../schedules/mutations/deleteSchedule.js";
import type * as schedules_mutations_runScheduleNow from "../schedules/mutations/runScheduleNow.js";
import type * as schedules_mutations_toggleGlobalPause from "../schedules/mutations/toggleGlobalPause.js";
import type * as schedules_mutations_toggleSchedule from "../schedules/mutations/toggleSchedule.js";
import type * as schedules_mutations_updateSchedule from "../schedules/mutations/updateSchedule.js";
import type * as schedules_mutations_updateScheduleNextRun from "../schedules/mutations/updateScheduleNextRun.js";
import type * as schedules_queries_getGlobalPauseStatus from "../schedules/queries/getGlobalPauseStatus.js";
import type * as schedules_queries_getGlobalPauseStatusInternal from "../schedules/queries/getGlobalPauseStatusInternal.js";
import type * as schedules_queries_getSchedule from "../schedules/queries/getSchedule.js";
import type * as schedules_queries_getScheduleHistory from "../schedules/queries/getScheduleHistory.js";
import type * as schedules_queries_getScheduleInternal from "../schedules/queries/getScheduleInternal.js";
import type * as schedules_queries_getUpcomingRuns from "../schedules/queries/getUpcomingRuns.js";
import type * as schedules_queries_listSchedules from "../schedules/queries/listSchedules.js";
import type * as schedules_queries_listStocksInternal from "../schedules/queries/listStocksInternal.js";
import type * as schedules_shared_computeNextRunAt from "../schedules/shared/computeNextRunAt.js";
import type * as schedules_shared_earningsConfigValidator from "../schedules/shared/earningsConfigValidator.js";
import type * as schedules_shared_getDatePartsInTimezone from "../schedules/shared/getDatePartsInTimezone.js";
import type * as schedules_shared_getUtcTimestampFromTzParts from "../schedules/shared/getUtcTimestampFromTzParts.js";
import type * as schedules_shared_matchesField from "../schedules/shared/matchesField.js";
import type * as schedules_shared_parseCron from "../schedules/shared/parseCron.js";
import type * as schedules_shared_parseField from "../schedules/shared/parseField.js";
import type * as schedules_shared_stockSelectionValidator from "../schedules/shared/stockSelectionValidator.js";
import type * as seed_mutations_backfillCostLogs from "../seed/mutations/backfillCostLogs.js";
import type * as seed_mutations_seedPrompts from "../seed/mutations/seedPrompts.js";
import type * as settings_mutations_upsertSetting from "../settings/mutations/upsertSetting.js";
import type * as settings_queries_getSetting from "../settings/queries/getSetting.js";
import type * as settings_shared_protectedSettingKeys from "../settings/shared/protectedSettingKeys.js";
import type * as stocks_actions_resolveStockSymbol from "../stocks/actions/resolveStockSymbol.js";
import type * as stocks_actions_searchStockSymbols from "../stocks/actions/searchStockSymbols.js";
import type * as stocks_mutations_addStock from "../stocks/mutations/addStock.js";
import type * as stocks_mutations_deleteStock from "../stocks/mutations/deleteStock.js";
import type * as stocks_mutations_updateStock from "../stocks/mutations/updateStock.js";
import type * as stocks_queries_getStock from "../stocks/queries/getStock.js";
import type * as stocks_queries_getStockByTicker from "../stocks/queries/getStockByTicker.js";
import type * as stocks_queries_listStocks from "../stocks/queries/listStocks.js";
import type * as stocks_queries_listTags from "../stocks/queries/listTags.js";
import type * as stocks_shared_getFinnhubApiKey from "../stocks/shared/getFinnhubApiKey.js";
import type * as stocks_shared_maxQueryLength from "../stocks/shared/maxQueryLength.js";
import type * as stocks_shared_minQueryLength from "../stocks/shared/minQueryLength.js";
import type * as stocks_shared_normalizeLookupQuery from "../stocks/shared/normalizeLookupQuery.js";
import type * as stocks_shared_requireValidSession from "../stocks/shared/requireValidSession.js";
import type * as validation from "../validation.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  auditLog: typeof auditLog;
  "auth/actions/changePassword": typeof auth_actions_changePassword;
  "auth/actions/login": typeof auth_actions_login;
  "auth/actions/logout": typeof auth_actions_logout;
  "auth/mutations/createSession": typeof auth_mutations_createSession;
  "auth/mutations/deleteSession": typeof auth_mutations_deleteSession;
  "auth/mutations/recordLoginAttempt": typeof auth_mutations_recordLoginAttempt;
  "auth/mutations/refreshSession": typeof auth_mutations_refreshSession;
  "auth/mutations/upsertSettingInternal": typeof auth_mutations_upsertSettingInternal;
  "auth/queries/checkLoginRateLimit": typeof auth_queries_checkLoginRateLimit;
  "auth/queries/getSettingValue": typeof auth_queries_getSettingValue;
  "auth/queries/validateSession": typeof auth_queries_validateSession;
  "auth/queries/validateSessionInternal": typeof auth_queries_validateSessionInternal;
  "auth/shared/computeLoginRateLimit": typeof auth_shared_computeLoginRateLimit;
  "auth/shared/generateToken": typeof auth_shared_generateToken;
  "auth/shared/getValidSession": typeof auth_shared_getValidSession;
  "auth/shared/rateLimitWindowMs": typeof auth_shared_rateLimitWindowMs;
  "auth/shared/requireAuth": typeof auth_shared_requireAuth;
  "auth/shared/sessionDurations": typeof auth_shared_sessionDurations;
  budgetAlert: typeof budgetAlert;
  "costTracking/mutations/markBudgetAlertSent": typeof costTracking_mutations_markBudgetAlertSent;
  "costTracking/queries/checkBudgetReachedInternal": typeof costTracking_queries_checkBudgetReachedInternal;
  "costTracking/queries/getCostByProvider": typeof costTracking_queries_getCostByProvider;
  "costTracking/queries/getCostHistory": typeof costTracking_queries_getCostHistory;
  "costTracking/queries/getMonthlyCost": typeof costTracking_queries_getMonthlyCost;
  "costTracking/queries/getMonthlyCostInternal": typeof costTracking_queries_getMonthlyCostInternal;
  "costTracking/shared/assertWithinBudget": typeof costTracking_shared_assertWithinBudget;
  "costTracking/shared/budgetReachedMessage": typeof costTracking_shared_budgetReachedMessage;
  "costTracking/shared/computeMonthlyCost": typeof costTracking_shared_computeMonthlyCost;
  "costTracking/shared/getBudgetThreshold": typeof costTracking_shared_getBudgetThreshold;
  "costTracking/shared/isMonthlyBudgetReached": typeof costTracking_shared_isMonthlyBudgetReached;
  crons: typeof crons;
  "dashboard/queries/activeJobsCount": typeof dashboard_queries_activeJobsCount;
  "dashboard/queries/monthlySpend": typeof dashboard_queries_monthlySpend;
  "dashboard/queries/recentResearch": typeof dashboard_queries_recentResearch;
  "dashboard/queries/upcomingSchedules": typeof dashboard_queries_upcomingSchedules;
  "earnings/actions/checkEarningsTriggers": typeof earnings_actions_checkEarningsTriggers;
  "earnings/actions/fetchAllEarnings": typeof earnings_actions_fetchAllEarnings;
  "earnings/actions/testCheckEarningsTriggers": typeof earnings_actions_testCheckEarningsTriggers;
  "earnings/mutations/recordTriggeredRun": typeof earnings_mutations_recordTriggeredRun;
  "earnings/mutations/updateScheduleLastRunAt": typeof earnings_mutations_updateScheduleLastRunAt;
  "earnings/mutations/upsertEarnings": typeof earnings_mutations_upsertEarnings;
  "earnings/queries/checkAlreadyTriggered": typeof earnings_queries_checkAlreadyTriggered;
  "earnings/queries/checkAlreadyTriggeredForQuarter": typeof earnings_queries_checkAlreadyTriggeredForQuarter;
  "earnings/queries/getEarningsByDate": typeof earnings_queries_getEarningsByDate;
  "earnings/queries/getEarningsByStockId": typeof earnings_queries_getEarningsByStockId;
  "earnings/queries/getEarningsForStocks": typeof earnings_queries_getEarningsForStocks;
  "earnings/queries/getEarningsSchedules": typeof earnings_queries_getEarningsSchedules;
  "earnings/queries/getEarningsSummaryAll": typeof earnings_queries_getEarningsSummaryAll;
  "earnings/queries/getStocksByIds": typeof earnings_queries_getStocksByIds;
  "earnings/queries/listAllStocksInternal": typeof earnings_queries_listAllStocksInternal;
  "earnings/shared/addDays": typeof earnings_shared_addDays;
  "earnings/shared/formatDate": typeof earnings_shared_formatDate;
  "earnings/shared/getCurrentReportingQuarter": typeof earnings_shared_getCurrentReportingQuarter;
  "earnings/shared/getQuarterKey": typeof earnings_shared_getQuarterKey;
  "earnings/shared/getTodayInTimezone": typeof earnings_shared_getTodayInTimezone;
  "earnings/shared/handleAggregateMode": typeof earnings_shared_handleAggregateMode;
  "earnings/shared/handleEachMode": typeof earnings_shared_handleEachMode;
  "earnings/shared/resolveEligibleStocks": typeof earnings_shared_resolveEligibleStocks;
  "earnings/shared/resolveSelectedStocks": typeof earnings_shared_resolveSelectedStocks;
  "earnings/shared/sleepMs": typeof earnings_shared_sleepMs;
  http: typeof http;
  "lib/anthropicBatchHelpers": typeof lib_anthropicBatchHelpers;
  "lib/asyncIterators": typeof lib_asyncIterators;
  "lib/exchangeTimezones": typeof lib_exchangeTimezones;
  "lib/finnhub/isEligibleType": typeof lib_finnhub_isEligibleType;
  "lib/finnhub/mapExchange": typeof lib_finnhub_mapExchange;
  "lib/finnhub/rankSearchResults": typeof lib_finnhub_rankSearchResults;
  "lib/finnhub/sortRank": typeof lib_finnhub_sortRank;
  "lib/finnhub/types": typeof lib_finnhub_types;
  "lib/logger": typeof lib_logger;
  "notifications/actions/detectTelegramChatId": typeof notifications_actions_detectTelegramChatId;
  "notifications/actions/dispatchBatchNotification": typeof notifications_actions_dispatchBatchNotification;
  "notifications/actions/dispatchJobNotification": typeof notifications_actions_dispatchJobNotification;
  "notifications/actions/sendEmail": typeof notifications_actions_sendEmail;
  "notifications/actions/sendTelegramMessage": typeof notifications_actions_sendTelegramMessage;
  "notifications/actions/sendTestEmail": typeof notifications_actions_sendTestEmail;
  "notifications/actions/sendTestTelegram": typeof notifications_actions_sendTestTelegram;
  "notifications/shared/buildResearchEmailHtml": typeof notifications_shared_buildResearchEmailHtml;
  "notifications/shared/escapeHtml": typeof notifications_shared_escapeHtml;
  "notifications/shared/formatDuration": typeof notifications_shared_formatDuration;
  "notifications/shared/sanitizeForTelegramMarkdown": typeof notifications_shared_sanitizeForTelegramMarkdown;
  "prompts/mutations/clonePrompt": typeof prompts_mutations_clonePrompt;
  "prompts/mutations/createPrompt": typeof prompts_mutations_createPrompt;
  "prompts/mutations/deletePrompt": typeof prompts_mutations_deletePrompt;
  "prompts/mutations/updatePrompt": typeof prompts_mutations_updatePrompt;
  "prompts/queries/getPrompt": typeof prompts_queries_getPrompt;
  "prompts/queries/getPromptInternal": typeof prompts_queries_getPromptInternal;
  "prompts/queries/listPrompts": typeof prompts_queries_listPrompts;
  "prompts/shared/promptType": typeof prompts_shared_promptType;
  "providers/anthropic": typeof providers_anthropic;
  "providers/anthropicManagedAgents": typeof providers_anthropicManagedAgents;
  "providers/anthropicManagedAgents/collectCompletedResult": typeof providers_anthropicManagedAgents_collectCompletedResult;
  "providers/anthropicManagedAgents/pickReportFile": typeof providers_anthropicManagedAgents_pickReportFile;
  "providers/anthropicManagedAgents/resolveIdleSession": typeof providers_anthropicManagedAgents_resolveIdleSession;
  "providers/anthropicModelLimits": typeof providers_anthropicModelLimits;
  "providers/constants": typeof providers_constants;
  "providers/formatOpenaiAdapter": typeof providers_formatOpenaiAdapter;
  "providers/index": typeof providers_index;
  "providers/managedAgentProvisioning/agentName": typeof providers_managedAgentProvisioning_agentName;
  "providers/managedAgentProvisioning/buildCoordinatorSystemPrompt": typeof providers_managedAgentProvisioning_buildCoordinatorSystemPrompt;
  "providers/managedAgentProvisioning/buildToolset": typeof providers_managedAgentProvisioning_buildToolset;
  "providers/managedAgentProvisioning/ensureAgent": typeof providers_managedAgentProvisioning_ensureAgent;
  "providers/managedAgentProvisioning/ensureEnvironment": typeof providers_managedAgentProvisioning_ensureEnvironment;
  "providers/managedAgentProvisioning/ensureManagedAgentResources": typeof providers_managedAgentProvisioning_ensureManagedAgentResources;
  "providers/managedAgentProvisioning/findAgentByName": typeof providers_managedAgentProvisioning_findAgentByName;
  "providers/managedAgentProvisioning/hashParams": typeof providers_managedAgentProvisioning_hashParams;
  "providers/openai": typeof providers_openai;
  "providers/openai/buildOpenAIResponseCreateParams": typeof providers_openai_buildOpenAIResponseCreateParams;
  "providers/openai/estimateOpenAICost": typeof providers_openai_estimateOpenAICost;
  "providers/openai/renderOutputTextWithCitations": typeof providers_openai_renderOutputTextWithCitations;
  "providers/openai/renderResearchMarkdown": typeof providers_openai_renderResearchMarkdown;
  "providers/openaiResponses": typeof providers_openaiResponses;
  "providers/types": typeof providers_types;
  "research/actions/checkJobHealth": typeof research_actions_checkJobHealth;
  "research/actions/pollFormat": typeof research_actions_pollFormat;
  "research/actions/pollJob": typeof research_actions_pollJob;
  "research/actions/processWebhookEvent": typeof research_actions_processWebhookEvent;
  "research/actions/recoverStaleFormatting": typeof research_actions_recoverStaleFormatting;
  "research/actions/recoverStaleJobs": typeof research_actions_recoverStaleJobs;
  "research/actions/reformatByTicker": typeof research_actions_reformatByTicker;
  "research/actions/reformatResearchJob": typeof research_actions_reformatResearchJob;
  "research/actions/startFormat": typeof research_actions_startFormat;
  "research/actions/startResearch": typeof research_actions_startResearch;
  "research/mutations/applyReformattedResult": typeof research_mutations_applyReformattedResult;
  "research/mutations/beginBackfillFormat": typeof research_mutations_beginBackfillFormat;
  "research/mutations/beginFormattingPhase": typeof research_mutations_beginFormattingPhase;
  "research/mutations/cancelJob": typeof research_mutations_cancelJob;
  "research/mutations/clearFormatExternalId": typeof research_mutations_clearFormatExternalId;
  "research/mutations/completeFormattedJob": typeof research_mutations_completeFormattedJob;
  "research/mutations/createAndStartResearch": typeof research_mutations_createAndStartResearch;
  "research/mutations/createResearchJob": typeof research_mutations_createResearchJob;
  "research/mutations/deleteJob": typeof research_mutations_deleteJob;
  "research/mutations/drainProviderQueue": typeof research_mutations_drainProviderQueue;
  "research/mutations/incrementAttempts": typeof research_mutations_incrementAttempts;
  "research/mutations/incrementFormatAttempts": typeof research_mutations_incrementFormatAttempts;
  "research/mutations/logCost": typeof research_mutations_logCost;
  "research/mutations/retryJob": typeof research_mutations_retryJob;
  "research/mutations/setFormatExternalId": typeof research_mutations_setFormatExternalId;
  "research/mutations/toggleFavorite": typeof research_mutations_toggleFavorite;
  "research/mutations/updateJobStatus": typeof research_mutations_updateJobStatus;
  "research/queries/debugJobFormatting": typeof research_queries_debugJobFormatting;
  "research/queries/debugListRecentJobs": typeof research_queries_debugListRecentJobs;
  "research/queries/findLatestCompletedJobByTicker": typeof research_queries_findLatestCompletedJobByTicker;
  "research/queries/getActiveJobs": typeof research_queries_getActiveJobs;
  "research/queries/getConcurrencyJobsInternal": typeof research_queries_getConcurrencyJobsInternal;
  "research/queries/getJob": typeof research_queries_getJob;
  "research/queries/getJobByExternalId": typeof research_queries_getJobByExternalId;
  "research/queries/getJobByFormatExternalId": typeof research_queries_getJobByFormatExternalId;
  "research/queries/getJobInternal": typeof research_queries_getJobInternal;
  "research/queries/getStaleFormattingJobs": typeof research_queries_getStaleFormattingJobs;
  "research/queries/getStaleRunningJobs": typeof research_queries_getStaleRunningJobs;
  "research/queries/getStockInternal": typeof research_queries_getStockInternal;
  "research/queries/listFavorites": typeof research_queries_listFavorites;
  "research/queries/listJobs": typeof research_queries_listJobs;
  "research/queries/listResults": typeof research_queries_listResults;
  "research/queries/searchResults": typeof research_queries_searchResults;
  "research/queries/summarizeResearchResultSizes": typeof research_queries_summarizeResearchResultSizes;
  "research/shared/applyCompletedResult": typeof research_shared_applyCompletedResult;
  "research/shared/applyFailedResult": typeof research_shared_applyFailedResult;
  "research/shared/clearFormatTrackingFields": typeof research_shared_clearFormatTrackingFields;
  "research/shared/completeFormatJob": typeof research_shared_completeFormatJob;
  "research/shared/countH2": typeof research_shared_countH2;
  "research/shared/countH3": typeof research_shared_countH3;
  "research/shared/dispatchPostCompleteSideEffects": typeof research_shared_dispatchPostCompleteSideEffects;
  "research/shared/formatMode": typeof research_shared_formatMode;
  "research/shared/formatPollInitialDelayMs": typeof research_shared_formatPollInitialDelayMs;
  "research/shared/getOpenAIApiKey": typeof research_shared_getOpenAIApiKey;
  "research/shared/getProviderApiKey": typeof research_shared_getProviderApiKey;
  "research/shared/handleFormatTimeout": typeof research_shared_handleFormatTimeout;
  "research/shared/handlePollCompleted": typeof research_shared_handlePollCompleted;
  "research/shared/handleStartError": typeof research_shared_handleStartError;
  "research/shared/isPipelineJob": typeof research_shared_isPipelineJob;
  "research/shared/isTerminal": typeof research_shared_isTerminal;
  "research/shared/jobHardTimeoutMs": typeof research_shared_jobHardTimeoutMs;
  "research/shared/jobStatus": typeof research_shared_jobStatus;
  "research/shared/loadActiveJobsForConcurrency": typeof research_shared_loadActiveJobsForConcurrency;
  "research/shared/loadDisplayActiveJobs": typeof research_shared_loadDisplayActiveJobs;
  "research/shared/loadFormattingJobs": typeof research_shared_loadFormattingJobs;
  "research/shared/loadJob": typeof research_shared_loadJob;
  "research/shared/loadJobForBackfill": typeof research_shared_loadJobForBackfill;
  "research/shared/maxRetries": typeof research_shared_maxRetries;
  "research/shared/maybeTimeoutOrReschedule": typeof research_shared_maybeTimeoutOrReschedule;
  "research/shared/missingKeyMessage": typeof research_shared_missingKeyMessage;
  "research/shared/parseRetryDelayMs": typeof research_shared_parseRetryDelayMs;
  "research/shared/reformatStarted": typeof research_shared_reformatStarted;
  "research/shared/resolvePrompt": typeof research_shared_resolvePrompt;
  "research/shared/schedulePoll": typeof research_shared_schedulePoll;
  "research/shared/scheduleProviderQueueDrain": typeof research_shared_scheduleProviderQueueDrain;
  "research/shared/scheduleStart": typeof research_shared_scheduleStart;
  "research/shared/sleep": typeof research_shared_sleep;
  "research/shared/sourceMarkdown": typeof research_shared_sourceMarkdown;
  "research/shared/statusMessage": typeof research_shared_statusMessage;
  researchConcurrency: typeof researchConcurrency;
  researchFormatCore: typeof researchFormatCore;
  researchFormatPrepass: typeof researchFormatPrepass;
  researchJobSearchMetadata: typeof researchJobSearchMetadata;
  "schedules/actions/executeRunNow": typeof schedules_actions_executeRunNow;
  "schedules/actions/executeScheduledRun": typeof schedules_actions_executeScheduledRun;
  "schedules/actions/scheduleNextRun": typeof schedules_actions_scheduleNextRun;
  "schedules/mutations/createSchedule": typeof schedules_mutations_createSchedule;
  "schedules/mutations/createScheduledJob": typeof schedules_mutations_createScheduledJob;
  "schedules/mutations/deleteSchedule": typeof schedules_mutations_deleteSchedule;
  "schedules/mutations/runScheduleNow": typeof schedules_mutations_runScheduleNow;
  "schedules/mutations/toggleGlobalPause": typeof schedules_mutations_toggleGlobalPause;
  "schedules/mutations/toggleSchedule": typeof schedules_mutations_toggleSchedule;
  "schedules/mutations/updateSchedule": typeof schedules_mutations_updateSchedule;
  "schedules/mutations/updateScheduleNextRun": typeof schedules_mutations_updateScheduleNextRun;
  "schedules/queries/getGlobalPauseStatus": typeof schedules_queries_getGlobalPauseStatus;
  "schedules/queries/getGlobalPauseStatusInternal": typeof schedules_queries_getGlobalPauseStatusInternal;
  "schedules/queries/getSchedule": typeof schedules_queries_getSchedule;
  "schedules/queries/getScheduleHistory": typeof schedules_queries_getScheduleHistory;
  "schedules/queries/getScheduleInternal": typeof schedules_queries_getScheduleInternal;
  "schedules/queries/getUpcomingRuns": typeof schedules_queries_getUpcomingRuns;
  "schedules/queries/listSchedules": typeof schedules_queries_listSchedules;
  "schedules/queries/listStocksInternal": typeof schedules_queries_listStocksInternal;
  "schedules/shared/computeNextRunAt": typeof schedules_shared_computeNextRunAt;
  "schedules/shared/earningsConfigValidator": typeof schedules_shared_earningsConfigValidator;
  "schedules/shared/getDatePartsInTimezone": typeof schedules_shared_getDatePartsInTimezone;
  "schedules/shared/getUtcTimestampFromTzParts": typeof schedules_shared_getUtcTimestampFromTzParts;
  "schedules/shared/matchesField": typeof schedules_shared_matchesField;
  "schedules/shared/parseCron": typeof schedules_shared_parseCron;
  "schedules/shared/parseField": typeof schedules_shared_parseField;
  "schedules/shared/stockSelectionValidator": typeof schedules_shared_stockSelectionValidator;
  "seed/mutations/backfillCostLogs": typeof seed_mutations_backfillCostLogs;
  "seed/mutations/seedPrompts": typeof seed_mutations_seedPrompts;
  "settings/mutations/upsertSetting": typeof settings_mutations_upsertSetting;
  "settings/queries/getSetting": typeof settings_queries_getSetting;
  "settings/shared/protectedSettingKeys": typeof settings_shared_protectedSettingKeys;
  "stocks/actions/resolveStockSymbol": typeof stocks_actions_resolveStockSymbol;
  "stocks/actions/searchStockSymbols": typeof stocks_actions_searchStockSymbols;
  "stocks/mutations/addStock": typeof stocks_mutations_addStock;
  "stocks/mutations/deleteStock": typeof stocks_mutations_deleteStock;
  "stocks/mutations/updateStock": typeof stocks_mutations_updateStock;
  "stocks/queries/getStock": typeof stocks_queries_getStock;
  "stocks/queries/getStockByTicker": typeof stocks_queries_getStockByTicker;
  "stocks/queries/listStocks": typeof stocks_queries_listStocks;
  "stocks/queries/listTags": typeof stocks_queries_listTags;
  "stocks/shared/getFinnhubApiKey": typeof stocks_shared_getFinnhubApiKey;
  "stocks/shared/maxQueryLength": typeof stocks_shared_maxQueryLength;
  "stocks/shared/minQueryLength": typeof stocks_shared_minQueryLength;
  "stocks/shared/normalizeLookupQuery": typeof stocks_shared_normalizeLookupQuery;
  "stocks/shared/requireValidSession": typeof stocks_shared_requireValidSession;
  validation: typeof validation;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {};
